version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: pycoach-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./course_materials:/app/course_materials
    networks:
      - pycoach-net

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: pycoach-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - pycoach-net

networks:
  pycoach-net:
    driver: bridge
